package com.agrosurvey.survey.data.mappers

import com.agrosurvey.survey.data.question.FieldType

fun FieldType?.toInt() : Int {

    return when(this) {
        is FieldType.ShortText -> 1
        is FieldType.LongText -> 2
        is FieldType.SelectBox -> 3
        is FieldType.RadioButton -> 4
        is FieldType.CheckedBox -> 5
        is FieldType.ReferenceDataResponses -> 6
        is FieldType.AutoGeneratedId -> 7
        is FieldType.Integer -> 8
        is FieldType.Decimal -> 9
        is FieldType.PhoneNumber -> 10
        is FieldType.DateTimePicker -> 11
        is FieldType.DatePicker -> 12
        is FieldType.TimePicker -> 13
        is FieldType.MonthPicker -> 14
        is FieldType.DayOfWeekPicker -> 15
        is FieldType.Signature -> 16
        is FieldType.Image -> 17
        is FieldType.Audio -> 18
        is FieldType.PolyGonPlot -> 19
        is FieldType.PathLine -> 20
        is FieldType.SinglePoint -> 21
        is FieldType.OneDimensionalTable -> 22
        is FieldType.TwoDimensionalTable -> 23
        is FieldType.BarCode -> 24
        is FieldType.QRCode -> 25
        is FieldType.PaymentButton -> 26
        is FieldType.Fingerprint -> 27
        is FieldType.Statement -> 28
        is FieldType.PdfFile -> 29
        is FieldType.None -> 0
        else -> 0
    }
}
fun FieldType.toStringFormat(): String {
    return when(this) {
        is FieldType.ShortText -> "short_text"
        is FieldType.LongText -> "long_text"
        is FieldType.SelectBox -> "select_box"
        is FieldType.RadioButton -> "radio_button"
        is FieldType.CheckedBox -> "checkbox"
        is FieldType.ReferenceDataResponses -> "reference_data_responses"
        is FieldType.AutoGeneratedId -> "auto_generated_id"
        is FieldType.Integer -> "integer"
        is FieldType.Decimal -> "decimal"
        is FieldType.PhoneNumber -> "phone_number"
        is FieldType.DateTimePicker -> "date_time_picker"
        is FieldType.DatePicker -> "date_picker"
        is FieldType.TimePicker -> "time_picker"
        is FieldType.MonthPicker -> "month_picker"
        is FieldType.DayOfWeekPicker -> "day_of_week_picker"
        is FieldType.Signature -> "signature"
        is FieldType.Image -> "image"
        is FieldType.Audio -> "audio"
        is FieldType.PolyGonPlot -> "polygon_plot"
        is FieldType.PathLine -> "path_line"
        is FieldType.SinglePoint -> "single_point"
        is FieldType.OneDimensionalTable -> "one_dimensional_table"
        is FieldType.TwoDimensionalTable -> "two_dimensional_table"
        is FieldType.BarCode -> "barcode"
        is FieldType.QRCode -> "qr_code"
        is FieldType.PaymentButton -> "payment_button"
        is FieldType.Fingerprint -> "finger_print"
        is FieldType.Statement -> "statement"
        is FieldType.PdfFile -> "pdf_file"
        is FieldType.None -> "unknown"
    }
}

fun String.toFieldType(): FieldType {
    return when(this) {
        "short_text" -> FieldType.ShortText
        "long_text" ->  FieldType.LongText
        "select_box" -> FieldType.SelectBox
        "radio_button" -> FieldType.RadioButton
        "reference_data_responses" -> FieldType.ReferenceDataResponses
        "checkbox" -> FieldType.CheckedBox
        "auto_generated_id" -> FieldType.AutoGeneratedId
        "integer" -> FieldType.Integer
        "decimal" -> FieldType.Decimal
        "phone_number" -> FieldType.PhoneNumber
        "date_time_picker" -> FieldType.DateTimePicker
        "date_picker" -> FieldType.DatePicker
        "time_picker" -> FieldType.TimePicker
        "month_picker" -> FieldType.MonthPicker
        "day_of_week_picker" -> FieldType.DayOfWeekPicker
        "signature" -> FieldType.Signature
        "image" -> FieldType.Image
        "audio" -> FieldType.Audio
        "polygon_plot" -> FieldType.PolyGonPlot
        "path_line" -> FieldType.PathLine
        "single_point" -> FieldType.SinglePoint
        "one_dimensional_table" -> FieldType.OneDimensionalTable
        "two_dimensional_table" -> FieldType.TwoDimensionalTable
        "barcode" -> FieldType.BarCode
        "qr_code" -> FieldType.QRCode
        "payment_button" -> FieldType.PaymentButton
        "finger_print" -> FieldType.Fingerprint
        "statement" -> FieldType.Statement
        "pdf_file" -> FieldType.PdfFile
        else -> FieldType.None
    }
}